fix 🐞: Fix issue with default config file path and add error handling for downloading default config file.

diff --git a/aimoji b/aimoji
--- a/aimoji
+++ b/aimoji
@@ -2,7 +2,7 @@
 
 # Set the config file path
 CONFIG_FILE_PATH=~/.aimojicommit/config.yaml
-REMOTE_DEFAULT_CONFIG_FILE_PATH=https://raw.githubusercontent.com/aimojicommit/main/config.yaml
+REMOTE_DEFAULT_CONFIG_FILE_PATH=https://raw.githubusercontent.com/Chiyo-no-sake/aiMojiCommit/main/config.yaml
 
 
 # Function to check and install dependencies
@@ -57,12 +57,19 @@ check_git_status() {
 # Function to create default config file
 create_default_config() {
     if [[ ! -f "$CONFIG_FILE_PATH" ]]; then
-        mkdir -p ~/.mojicommit
-        wget "$REMOTE_DEFAULT_CONFIG_FILE_PATH" > "$CONFIG_FILE_PATH"
+        mkdir -p ~/.aimojicommit
+        wget --quiet -O $CONFIG_FILE_PATH "$REMOTE_DEFAULT_CONFIG_FILE_PATH"
+
+        if [[ $? -ne 0 ]]; then
+            echo "Error: Failed to download the default config file. Exiting." >&2
+            rm "$CONFIG_FILE_PATH"
+            exit 1
+        fi
 
         echo "It appears to be the first time you run $0."
         read -p "Enter your OpenAI API key (press Enter to skip -> disable AI commit gen): " openAIKey
-        echo "openAIKey: '$openAIKey'" >> "$CONFIG_FILE_PATH"
+        echo "" >> $CONFIG_FILE_PATH
+        echo "openAIKey: $openAIKey" >> $CONFIG_FILE_PATH
     fi
 }
 
@@ -88,7 +95,7 @@ import sys
 import os
 
 def load_api_key():
-    api_key_file = os.path.expanduser('~/.mojicommit/config.yaml')
+    api_key_file = os.path.expanduser("$CONFIG_FILE_PATH")
     with open(api_key_file) as file:
         api_key = yaml.safe_load(file)
     return api_key['openAIKey']
@@ -167,12 +174,12 @@ make_commit() {
         echo -n "$COMMIT_MESSAGE" >> $TEMP_FILE
 
         # Use the temporary file as the commit message template
-        git commit -et $TEMP_FILE
+        git commit -eF $TEMP_FILE
 
         # Remove the temporary file
         rm $TEMP_FILE
     else
-        git commit -et $TEMP_FILE
+        git commit -eF $TEMP_FILE
         rm $TEMP_FILE
     fi
 }
